# GoReleaser configuration for jp
# See: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - id: jp
    main: ./cmd/jp
    binary: jp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude invalid combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      # Strip debug info for smaller binaries
      - -s -w
      # Include version information
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: jp-archive
    formats:
      - tar.gz
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: arnodel
    name: jsonstream
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## jp {{.Version}}

    Download pre-built binaries below or install using Go:
    ```bash
    go install github.com/arnodel/jsonstream/cmd/jp@{{.Tag}}
    ```
  footer: |
    **Full Changelog**: https://github.com/arnodel/jsonstream/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap configuration
#
# Setup required (one-time):
# 1. Create a public GitHub repository: arnodel/homebrew-tap
#    - Repository can be empty, GoReleaser will populate it
# 2. Create a Personal Access Token (fine-grained tokens recommended):
#    - Go to GitHub Settings → Developer settings → Personal access tokens → Fine-grained tokens
#    - Generate new token with:
#      * Repository access: Only select repositories → homebrew-tap
#      * Repository permissions: Contents (Read and write), Metadata (Read)
#    - Alternative: Classic token with 'repo' scope (less secure, grants broader access)
# 3. Add token as repository secret to arnodel/jsonstream:
#    - Go to jsonstream repo → Settings → Secrets and variables → Actions
#    - Add secret named 'TAP_GITHUB_TOKEN' with the token value
# 4. Update .github/workflows/release.yaml to pass token:
#    - Add 'TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}' to env section
#
# How it works:
# - On each release, GoReleaser automatically creates/updates Casks/jp.rb in homebrew-tap
# - Users can then install with: brew install arnodel/tap/jp
homebrew_casks:
  - ids:
      - jp-brew
    repository:
      owner: arnodel
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    description: "JSON stream processor and transformation tool"
    homepage: "https://github.com/arnodel/jsonstream"
    license: "Apache-2.0"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "jp"
    test: |
      system "echo '{}' | #{bin}/jp"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jp"]
          end
