name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: All tests
      run: go test -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.txt
        name: codecov-all-tests
        verbose: true
